[iOS] Coordinator 패턴 구현
pbg0205/issue-tracker pull request #8
Opened 2021-06-08 07:24 UTC by dahun-lee-daji

# 구현 사항
- [x] protocol Coordinator
- [x] class IssueCoordinator: Coordinator ( 예시로 만들어 낸 Class)
- [x] class: Coordinator를 모아서 rootViewController가 될 MainTabBarController

2021-06-08 15:15 UTC, ellyheetov requested changes
Coordinator 패턴을 사용하고 싶으셨던 것 같은데, 만든 Coordinator를 사용하고 있는 부분은 확인할 수 없네요🥲

Coordinator 패턴은 ViewController의 책임을 줄여주기 위해서 화면전환의 역할을 Coordinator에게 맡겼다고 보시면 되요.
그럼 이제, Coordinator는 맡은 임무를 수행해야 겠죠. Coordinator는 본인의 NavigationController를 가지고 있고, 파라미터로 넘어온 새로운 viewController를 본인의 NavigationController에 추가해 주는 거예요. push가 되는 순간에 화면이 전환이 되니까 임무를 잘 수행한거겠죠.

coordinator에 있는 메소드를 호출하기 위해서는 새로운 ViewController가 coordinator를 알고 있어야 하고, 그렇기 때문에 `weak var coordinator: Coordinator?` 변수를 가지고 있는 거예요. 

저도 그랬지만, 코드는 몇줄 안돼도 설계하는 시간은 꾀 오래걸리는 것 같아요. 다시 한번 생각해보고 수정해봐요!

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Coordinator/Coordinator.swift
> +  }
navigationController를 파라미터로 받고
파라미터로 받은 네비게이션 컨트롤러에 같은 네비게이션 컨트롤러를 추가하고 있는 건가요?

코디네이터 패턴은 중심이 되는 네비게이션 컨트롤러(또는 탭바 컨트롤러)를 가지고 있고, 
그 컨트롤러에 push 시켜주는 방법이라고 생각해요. 
```swift
protocol Coordinator {
    var navigationController: UINavigationController { get set }

    func pushToNavigationViewController()
}
```
지금과 같은 경우 navigationController를 인자로 받고 있는데, 함수내에서 그 컨트롤러에 같은 컨트롤러를 또 push하고 있는걸로 보이네요.

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Controller/MainTabBarController.swift
> +    }
childCoordinator를 둔다던지, tabbar의 viewControllers를 생성하는 조금 더 유연한 방법을 찾아보는게 좋을 것 같네요!

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Controller/ViewController.swift
> +
coordinator는 마치 화면을 전환하는 델리게이션이라고도 볼 수 있어요.
ViewController에 대한 참조 카운트가 증가하게 되기 때문에 coordinator 변수는 weak로 선언해야 합니다.

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Coordinator/IssueCoordinator.swift
> +    }
여기서 navigationController는 self.navigationController인지 파라미터로 넘어온 navigationController인지 명시적으로 구별 해주시면 좋겠어요.

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Coordinator/IssueCoordinator.swift
> +    }
Coordinator 클래스에서 아래 코드가 동작 할 수 있었던건, self.navigationController가 있었기 때문이 아닐까 추측이 되네요.
```swift
func pushToView(_ navigationController: UINavigationController, title: String) {
    let vc = navigationController
    navigationController.pushViewController(vc, animated: true)
}
```

2021-06-08 15:15 UTC, ellyheetov commented on iOS/issue-tracker/Presenter/Controller/MainTabBarController.swift
> +
coordinator를 ViewController안에서 생성한다? 뭔가 좀 이상한데요?

2021-06-09 10:08 UTC, dahun-lee-daji commented on iOS/issue-tracker/Presenter/Coordinator/Coordinator.swift
> +  }
홀리몰리!
이 바보짓은 수정되었스빈다 (^///^)

2021-06-09 10:10 UTC, dahun-lee-daji commented on iOS/issue-tracker/Presenter/Controller/ViewController.swift
> +
음,,, 조금 더 상세한 설명을 요청드려도 괜찮을까요?

2021-06-09 10:11 UTC, dahun-lee-daji commented on iOS/issue-tracker/Presenter/Coordinator/IssueCoordinator.swift
> +    }
해당된 내용은 수정되었습니다! 아마도?..

2021-06-09 10:15 UTC, dahun-lee-daji commented on iOS/issue-tracker/Presenter/Controller/MainTabBarController.swift
> +
현재로는 TabBar를 통한 뷰 이동에 
self.viewControllers = [ 각Coordinator.navigationController] 를 통해 TabBarItem에 등록되고 있습니다. 때문에, 이와 같은 일이 벌어졌습니다. 
Coordinator 내부에 navigationController가 있기 때문입니다.

추가적인 해결 방안이 생각나지 않는데 의견 있으신지 궁금합니다!

2021-06-11 07:20 UTC, dahun-lee-daji commented
머지 완료.

2021-06-11 07:20 UTC, closed without merging